branches:
  only:
    - master

version: 0.0.8-{build}

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8.11.2 x64
  - npm install

build_script:
  - npm run build-windows

test: off
